secret = "plzchange 32 or 64 bytes is best"
database = "./alexandria-db"
library = "./alexandria-books"

[uberich]
appName = "alexandria"
appURL = "https://alexandria.example.com"
uberichURL = "https://uberich.example.com"
secret = "shared app secret"
